language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install: 
  - pip install git+https://github.com/rrwen/kwconfig
  - pip install coveralls
script:
  - coverage run --source=kwconfig -m unittest
after_success:
  - coveralls
